# Use an official Python image
FROM python:3.11-slim

WORKDIR /executor

# Copy required dependencies
COPY execute_code.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "execute_code.py"]
